name: CI

on: push

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    
    env:
      COVERITY: coverity_tool

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Compile Test and Verify
        run: mvn clean verify
        
  coverity:
    needs: verify
  
    name: Coverity
    runs-on: ubuntu-latest
    
    env:
      COVERITY: coverity_tool
      
    steps:
      - name: Download Coverity
        if: hashFiles('$COVERITY/VERSION.xml') == ''
        run: wget https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=rlp_01" -O coverity_tool.tgz && tar zxvf $COVERITY.tgz
        
      - name: Cache Coverity
        uses: actions/cache@v2
        with:
          path: ~/coverity_analysis_linux
          key: ${{ runner.os }}-coverity-${{ hashFiles('$COVERITY/VERSION.xml') }}
          restore-keys: ${{ runner.os }}-coverity-
          
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
