name: Test and Release

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test
        run: mvn clean test

  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Package
      run: mvn clean package

    - name: Verify
      run: mvn verify
      
    - name: Setup Maven Central
      if: github.ref == 'refs/heads/master'
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
        server-id: # This should match the id of the repository Maven is connecting to
        server-username: ${{ secrets.MAVEN_USERNAME }}
        server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }} # Delete if you are using a gpg private key to login
        
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: mvn deploy
