name: Upload Release

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup Signing
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Setup GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to GitHub Packages
        run: mvn --batch-mode -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= clean deploy -Ppublish-github-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


      - name: Setup Maven Central
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'

          server-id: central-sonatype-org
          server-username: CENTRAL_SONATYPE_ORG_USERNAME
          server-password: CENTRAL_SONATYPE_ORG_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Maven Central
        run: mvn --batch-mode -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= clean deploy -Ppublish-maven-central
        env:
          CENTRAL_SONATYPE_ORG_USERNAME: ${{ secrets.CENTRAL_SONATYPE_ORG_USERNAME }}
          CENTRAL_SONATYPE_ORG_PASSWORD: ${{ secrets.CENTRAL_SONATYPE_ORG_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

